### ISSUE TITLE
Connection Screen - Connect Button Issues

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#10]
1) Label of Connect/Disconnect button does not change back to "Connect" after Disconnecting:

![image](https://user-images.githubusercontent.com/12492529/56869101-15354b00-69fc-11e9-9da6-7ae1c96a1e47.png)

Reproduce:
- Connect
- Disconnect

Label of button remains "Disconnect", even though already disconnected.

2) During connection, the button is not greyed out.

It looks like this in the Java FX version:
![image](https://user-images.githubusercontent.com/12492529/56869135-ce942080-69fc-11e9-8dad-81397085f9a3.png)

Here is how it looks during connect in the current version:
![image](https://user-images.githubusercontent.com/12492529/56869145-04390980-69fd-11e9-80bb-0582263d5234.png)

**Comment by flogat** [comment]
This applies also to the whole top area "Connected Since..." etc. - this information should also be reset to "Disconnected" info

**Comment by Tcheutchoua-Steve** [comment]
Resolved with commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/a55ba898ff699e1f5d23c6a04949cba029fea511
