### ISSUE TITLE
No progress bar when connecting

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#11]
While connecting, the current Java Swing version shows a progress bar:
![image](https://user-images.githubusercontent.com/12492529/56869155-30ed2100-69fd-11e9-9870-b42be6c0debb.png)

The current JavaFX version does only show a spinning mouse cursor.

Please implement the Progress Bar

**Comment by Tcheutchoua-Steve** [comment]
In progress
