### ISSUE TITLE
No progress bar for endpoint finding

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#12]
The current Java Swing version of the app shows a progress bar during the period where the best webservice endpoint is identified:
![image](https://user-images.githubusercontent.com/12492529/56869234-4c0c6080-69fe-11e9-8583-322d56b98d0e.png)

Please add to the FX version.

**Comment by Tcheutchoua-Steve** [comment]
In progress

**Comment by Tcheutchoua-Steve** [comment]
Testing endpoints showing now.

**Comment by Tcheutchoua-Steve** [comment]
This has already been resolved
