### ISSUE TITLE
Server List Table -  currently selected server not selected when menu item is loaded

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#13]
When the Server List is loaded, the already selected server for the currently chosen VPN account should be preselected. (This is the case in the Swing version). In the current FX version, nothing is pre-selected on load. 

Please impleemt

**Comment by Tcheutchoua-Steve** [comment]
In progress

**Comment by Tcheutchoua-Steve** [comment]
Currently selected server chosen when server list  is loaded
