### ISSUE TITLE
Server List Table - table not locked while connection state is "connecting" or "connected"

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#14]
In the Swing version of the app, in connection modes "Connecting" and "Connected", the server list is greyed out / disabled. Please implement:
![image](https://user-images.githubusercontent.com/12492529/56869269-dbb20f00-69fe-11e9-81cd-65d1e677c7b3.png)

**Comment by Tcheutchoua-Steve** [comment]
In progress

**Comment by Tcheutchoua-Steve** [comment]
Solved in commit  fb954f4
