### ISSUE TITLE
Server List Table - Connect Button Issues

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#15]
The Connect Button on the Server List Table menu item should by synchronized with the connect button on the "Connection" / Main menu item.

**Comment by Tcheutchoua-Steve** [comment]
In progress

**Comment by Tcheutchoua-Steve** [comment]
Solved with commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/a55ba898ff699e1f5d23c6a04949cba029fea511
