### ISSUE TITLE
server table entries selection not changing when clicking on country column

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#25]
Changing the selected server entry only works when clicking on columns Name, Server, Security, Speed, but when trgying to select a server by clicking on Country column, selection is not changed.

Please fix.

**Comment by Tcheutchoua-Steve** [comment]
Resolved in https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/42291ea10a5dcc0b9a684493c4eb39711b9af858
