### ISSUE TITLE
showconsole  not working

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#26]
When typing "showconsole", the console window (basically a logfile-viewer) should appear.

Current behavior: console does not appear
Please fix.

**Comment by Tcheutchoua-Steve** [comment]
In progress

**Comment by Tcheutchoua-Steve** [comment]
@flogat could you please explain the intended function of this method? [getPathJar]( https://github.com/shell-fire/shellfire-vpn/blob/master/ShellfireVPN/src/main/java/de/shellfire/vpn/Util.java#L634)
Also, why does the function return null [here](https://github.com/shell-fire/shellfire-vpn/blob/master/ShellfireVPN/src/main/java/de/shellfire/vpn/Util.java#L645)

**Comment by flogat** [comment]
When compiled into a fat jar, this function returns the path to the currently loaded jar file.

Check this stackoverflow response for some details: https://stackoverflow.com/a/1983875/812866

Why is this needed for showconsole?

**Comment by Tcheutchoua-Steve** [comment]
Thanks
It is instead needed for issue #27 not this one.

**Comment by Tcheutchoua-Steve** [comment]
Resolved in commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/ef20a9f10ccf688b9029ff68215fec905457c8c0
