### ISSUE TITLE
installElevated to install shellfire service is not working

### ISSUE THREAD

**Issue by Tcheutchoua-Steve** [Tcheutchoua-Steve/shellfire-vpn#27]
At startup, when the shellfire service is not functional and needs to be installed an error message occurs in both swing and JavaFX versions. It should be looked upon.

**Comment by flogat** [comment]
This functionality is supposed to only work in the built/installed version. 
Functionality is as follows:
- Call an elevate.vbs script, that asks the user for admin privileges, which will then re-spawn basically "java -jar ShellfireVPN2Service.dat installservice" - this cannot work from an IDE environment.

From my perspective, you can close this one, not in scope of your job :)

**Comment by Tcheutchoua-Steve** [comment]
Cool. Thanks for the info :smile:
