### ISSUE TITLE
SettingsDialog: Current Language not selected

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#35]
The SettingsDialog does not show the currently chosen language:
![image](https://user-images.githubusercontent.com/12492529/70395857-7e098a80-1a03-11ea-9453-f98c1bd5d170.png)

In the JDialog version (Swing) I programmed before, this was implemented in the following way in the initLanguages() method:
```
    private void initLanguages() {
...
        jLanguageComboBox.setSelectedItem(currentLanguage);
    }    
```
 
Please add this functionality.

**Comment by Tcheutchoua-Steve** [comment]
Hi @flogat may I know the purpose of the JOptionPane here https://github.com/Tcheutchoua-Steve/shellfire-vpn/blob/ad568d3a827db848d3a43fe4c6b0536c20297408/ShellfireVPN/src/main/java/de/shellfire/vpn/i18n/VpnI18N.java#L33 and https://github.com/Tcheutchoua-Steve/shellfire-vpn/blob/ad568d3a827db848d3a43fe4c6b0536c20297408/ShellfireVPN/src/main/java/de/shellfire/vpn/i18n/VpnI18N.java#L99 ?

**Comment by flogat** [comment]
Sure - when a user has changed the language in the dropdown, we cannot change the language in the whole Swing application. Therefore, we have to ask the user if he would like to restart the application.

However, we want to present the "ask-for-restart" dialog in the changed-to language. Therefore we manually set a new locale on all JOptionPange dialogs.

Makes sense?

**Comment by Tcheutchoua-Steve** [comment]
🙂 
it makes much sense now.

**Comment by Tcheutchoua-Steve** [comment]
Resolved in commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/40fbf8fb807e67d70b33d0e1e9a4a138e41e548e
