### ISSUE TITLE
Settings Dialog: Changing language Yes/No Dialog not working correctly

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#36]
When changing the selected language, a Dialog appears that asks the user if he wants to restart the application to perform the language switch. This dialog has no buttons and the only way forward is to quit the javaw.exe process via Task Manager.

Is: 
![image](https://user-images.githubusercontent.com/12492529/70395903-ed7f7a00-1a03-11ea-9985-6cf20d1fb00e.png)

Should: 
![image](https://user-images.githubusercontent.com/12492529/70395979-ad6cc700-1a04-11ea-99e3-edc87d9d39ff.png)

Please fix.

**Comment by Tcheutchoua-Steve** [comment]
Resolved even earlier than this commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/40fbf8fb807e67d70b33d0e1e9a4a138e41e548e
