### ISSUE TITLE
Settings Dialog: Languages listed twice

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#37]
The language dropdown contains each language twice - please fix.

Is:
![image](https://user-images.githubusercontent.com/12492529/70396005-fe7cbb00-1a04-11ea-9772-848490a82e74.png)

Should - list of languages contains each language only once:
![image](https://user-images.githubusercontent.com/12492529/70396009-0d636d80-1a05-11ea-9ec9-2abdd7845e0a.png)

Please fix.

**Comment by Tcheutchoua-Steve** [comment]
This should be due to a recent commit. It has been showing each language once. I will fix it.

**Comment by Tcheutchoua-Steve** [comment]
Resolved in commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/ad568d3a827db848d3a43fe4c6b0536c20297408
