### ISSUE TITLE
Make Every string translatable

### ISSUE THREAD

**Issue by Tcheutchoua-Steve** [Tcheutchoua-Steve/shellfire-vpn#38]
Some strings and inputs are fixed in English/German. Changing the language of the application does not change the String. 
This should be adjusted.

**Comment by flogat** [comment]
Some notes to this:
This is usually as easy as 
1) replacing the actual string by i18n(string).
2) What I then do is, with POEDIT, to parse the source code of all files again and then the new translations will appear in the po files. 
They are stored in the build-scripts/lang folder.
3) With the msgfmt.sh script then (which runs on cygwin on Windows), the Messages_XX.class files are compiled which I sent you a couple of days ago.

Please do not try to get the msgfmt.sh script running yourself. This is a tedious task and involves setting up a fully-fledged cygwin environment on your Windows machine, something that will take hour over hour.

So once you added new translations as described above in 1), just let me know and I will perform the steps 2) and 3).


Note: In case a certain string is not translated in the Messages_XX.class file, the string will simply not be translated.

Note 2: At some point during the project, we agreed to have all language strings in the source code in english, Please adhere to that.

**Comment by Tcheutchoua-Steve** [comment]
Thanks for clarifying. 
I will focus on 1) and maintain the strings in English as agreed.

**Comment by Tcheutchoua-Steve** [comment]
Strings have been changed to English language, before or on commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/90f286af5ac8feb1896789f0e0a588771e1eca08
