### ISSUE TITLE
German text in MainFormController

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#39]
https://github.com/Tcheutchoua-Steve/shellfire-vpn/blob/40fbf8fb807e67d70b33d0e1e9a4a138e41e548e/ShellfireVPN/src/main/java/de/shellfire/vpn/gui/controller/ShellfireVPNMainFormFxmlController.java#L659

Dieser Server steht nur für Shellfire VPN Premium Kunden zur Verfügung\n\nWeitere Informationen zu Shellfire VPN Premium anzeigen?

please replace by

This server is only available for clients of Shellfire VPN Premium.\n\nShow more information about Shellfire VPN Premium?

**Comment by flogat** [comment]
Ideally, the linebreaks could be avoided in the string and the javafx controller takes care of proper linebreaks that do not cause trouble with the layout.

**Comment by Tcheutchoua-Steve** [comment]
I am figuring out the layout adaptation to string lengths. I also noticed it will be necessary when switching languages because some languages make the strings to display much longer.

**Comment by Tcheutchoua-Steve** [comment]
Resolved on or before commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/90f286af5ac8feb1896789f0e0a588771e1eca08
