### ISSUE TITLE
German text in VpnSelectDialogController

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#40]
https://github.com/Tcheutchoua-Steve/shellfire-vpn/blob/40fbf8fb807e67d70b33d0e1e9a4a138e41e548e/ShellfireVPN/src/main/java/de/shellfire/vpn/gui/controller/VpnSelectDialogController.java#L190

In deinem Shellfire Account wurden mehrere VPN gefunden.\nBitte wähle den VPN aus, den du benutzen möchtest

please replace by

Multiple VPNs have been found In your Shellfire account.\nPlease select the vpn you would like to use.

**Comment by flogat** [comment]
Ideally, the linebreaks could be avoided in the string and the javafx controller takes care of proper linebreaks that do not cause trouble with the layout.

**Comment by Tcheutchoua-Steve** [comment]
Resolved on or before commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/90f286af5ac8feb1896789f0e0a588771e1eca08
