### ISSUE TITLE
German Text in VpnSelectDialogController 2

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#41]
https://github.com/Tcheutchoua-Steve/shellfire-vpn/blob/40fbf8fb807e67d70b33d0e1e9a4a138e41e548e/ShellfireVPN/src/main/java/de/shellfire/vpn/gui/controller/VpnSelectDialogController.java#L196

"Hinweis: Die VPN Typen PPTP und L2TP/IPSec müssen \n nach der Auswahl zunächst auf OpenVPN gewechselt werden,\n damit sf vpn die Verbindung herstellen kann."
   
should be

"Attention: The VPN Types PPTP and L2TP/IPsec have to be\nswitched back to OpenVPN so that\n Shellfire VPN can connect to them again."

Ideally, the linebreaks could be avoided in the string and the javafx controller takes care of proper linebreaks that do not cause trouble with the layout.

**Comment by Tcheutchoua-Steve** [comment]
Resolved before or on commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/90f286af5ac8feb1896789f0e0a588771e1eca08
