### ISSUE TITLE
SettingsDialog - language picker - always switches to german

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#42]
In the settings dialog, which is loaded and looks like this for example with french as currently selected language:
![image](https://user-images.githubusercontent.com/12492529/71561437-bcc8b880-2a76-11ea-857f-5c031363c625.png)

However, when I click on the arrow next to the language display, it automatically selects "Deutsch" (German):
![image](https://user-images.githubusercontent.com/12492529/71561439-cf42f200-2a76-11ea-98a1-8ef191b35471.png)

Please change so that clicking the arrow to open the drop down does not already change the current selection.

**Comment by Tcheutchoua-Steve** [comment]
Resolved in commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/095ca4a7392e08b8ea538da31208e6b82dd0f8c2
