### ISSUE TITLE
SettingsDialog: LanguagePicker - Languages displayed in German

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#43]
The languages in the language picker are in German:
![image](https://user-images.githubusercontent.com/12492529/71561472-06190800-2a77-11ea-99e4-9383319dba56.png)

Please change so that the languages are displayed in the currently selected language (means: the displayed texts also need to be translated from english to current-language.

**Comment by Tcheutchoua-Steve** [comment]
This is pretty much the same in the current swing version @Florian. The languages are also displayed in German.

**Comment by Tcheutchoua-Steve** [comment]
Is it something that still needs to be changed?

**Comment by florian** [comment]
Pretty sure you wanted to @ mention someone else.

**Comment by flogat** [comment]
Yes, please implement even if not right in current swing version, thanks!

**Comment by Tcheutchoua-Steve** [comment]
Oh yeah, I wanted to mention @flogat :)

**Comment by Tcheutchoua-Steve** [comment]
Resolved in commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/d211535d818c648c92dca2c699361f720e4e7964
