### ISSUE TITLE
SettingsDialog: Language label not translated

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#44]
The language label next to the drop down language-picker is not translated:
![image](https://user-images.githubusercontent.com/12492529/71561514-c9014580-2a77-11ea-86f1-80455a78695b.png)

Please implement translation.

**Comment by flogat** [comment]
Also valid for the "Connect Automatically" label
![image](https://user-images.githubusercontent.com/12492529/71561522-e6361400-2a77-11ea-9e43-33cf587a6913.png)

**Comment by Tcheutchoua-Steve** [comment]
Resolved in commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/dd96c242779f98d9a7caf7b57a83a1f6053817f5
