### ISSUE TITLE
SettingsDialog: Layout

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#45]
The Layout of the settings dialog is not cleaned up. Please implement a cleanup, considering button sizes, margins, etc.

You can get some ideas of what I mean in this annotated screenshots - but it is not complete:
![image](https://user-images.githubusercontent.com/12492529/71561562-9c99f900-2a78-11ea-9dc9-088543fb7bac.png)

**Comment by Tcheutchoua-Steve** [comment]
Resolved in commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/eaf52073ee0abe8e7343a6e8c3218d674b5c2d72
