### ISSUE TITLE
ServerList: Sorting by Country not working properly

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#46]
In the serverlist, when sorting the table by country, the sorting actually occurs by server-number:

![image](https://user-images.githubusercontent.com/12492529/71561635-4bd6d000-2a79-11ea-9082-bd1ed0c00622.png)

Please implement in the following way:
Sorting occurs by **translated** name of country.

**Comment by Tcheutchoua-Steve** [comment]
Sorting by country is resolved in commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/16b207bfe027e9ca76d43a43e2596923da0dfc51

**Comment by Tcheutchoua-Steve** [comment]
Hi @flogat, do we need to sort other table columns or sorting by the country is enough?
