### ISSUE TITLE
Main Menu: Text is shortened by ellipsis

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#47]
In the main menu, the text is too long and therefore shortened by an ellipsis (...):
![image](https://user-images.githubusercontent.com/12492529/71561663-c4d62780-2a79-11ea-931f-afc4dbc9c9e1.png)

Please fix, ideally by implementing a linebreak for the description text of the menu item. But there are some more ideas about what could be done in the screenshot, please take a look.

**Comment by Tcheutchoua-Steve** [comment]
Resolved in commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/e1bd1ae3c5f1c34a41eb7c8961a3a9947dba799b
