### ISSUE TITLE
Main Window: Top left logo not translated

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#48]
In the top left corner of the application, the image is shown that shows the text
Shellfire VPN 
easy. safe. connected.

![image](https://user-images.githubusercontent.com/12492529/71561693-15e61b80-2a7a-11ea-8c31-66449d7d93d3.png)

However, this is an image that is available also translated into german and french. 

The translated versions are located here:
\src\main\resources\icons
sf.png - German
sf_en.png - English
sf_fr.png French

I suggest to change the name of sf.png to sf_de.png which allows adding more languages later more easily.

Please implement loading of the respective resource depending on the currently selected language.

**Comment by Tcheutchoua-Steve** [comment]
Resolved in commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/5b0aec20323c6bb9e6b7b50b578a7a850d9beb5c
