### ISSUE TITLE
Application Name is "Shellfire VPN 2 Login"

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#49]
When the main application is launched based on LoginForms JAva FX code, it is displayed in the Task Bar as "Shellfire VPN 2 Login".
![image](https://user-images.githubusercontent.com/12492529/71561733-8bea8280-2a7a-11ea-92de-b9bd27b44fbd.png)

Please implement, so that the display here is only "Shellfire VPN"

**Comment by Tcheutchoua-Steve** [comment]
That is pretty much what I saw in the swing version https://github.com/shell-fire/shellfire-vpn/blob/master/ShellfireVPN/src/main/java/de/shellfire/vpn/gui/LoginForm.java#L352

**Comment by Tcheutchoua-Steve** [comment]
It has now been adjusted to "Shellfire VPN"

**Comment by Tcheutchoua-Steve** [comment]
Resolved in commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/972839f488f7fecf36020050ac78f5e94eb8de32

**Comment by Tcheutchoua-Steve** [comment]
Resolved in https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/cc4c25c60fe96d8de59b137cdc91620f058dd313
