### ISSUE TITLE
SettingsDialog: When changing language, user is asked 2 times to confirm restart

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#50]
In the SettingsDialog, when changing the currently selected language, the Confirmation dialog is displayed 2 times:

![image](https://user-images.githubusercontent.com/12492529/71561748-c94f1000-2a7a-11ea-8fad-3cb6493f76cc.png)

Then, when clicking on okay, the dialog appears again:
![image](https://user-images.githubusercontent.com/12492529/71561755-d409a500-2a7a-11ea-96d8-1f4ac713d821.png)

When run from Netbeans, an error message is thrown, which is okay. I just ran it from the installed build (as exe, etc. ) and here the restart works fine.

Please implement so that this dialog is only shown 1 time.

**Comment by Tcheutchoua-Steve** [comment]
Resolved in commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/d415196f48cb7f85733004dce4304e7ac7dfc240
