### ISSUE TITLE
EndPointDialog / ProgressDialog: Layout

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#51]
This is how the EndpointDialog currently looks:
![image](https://user-images.githubusercontent.com/12492529/71561774-45e1ee80-2a7b-11ea-80c6-10b167adf1a2.png)

The whitespace/margin below the progressbar should be removed. I assume this is there for the placeholder of the optional buttons/texts that can be shown there. However, when these buttons are not shown, the space reserved for them should also not be used.

In Swing this would have been achieved with some type of "pack()" functionality, which in JavaFX I assume something similar exists. I found this article here which explains some changes between JavaFX 1.2 and 1.3 for autosizing of components, maybe this is worth checking out:
https://amyfowlersblog.wordpress.com/2010/05/07/javafx-1-3-autosizing-everywhere/

**Comment by Tcheutchoua-Steve** [comment]
Resolved in commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/034a94db5d466dd3c5d94857bb33ddf6919b395a
