### ISSUE TITLE
ServerListTable - background color of selected rows does not change

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#6]
Just for the sake of completion - you're already on it ;)

**Comment by Tcheutchoua-Steve** [comment]
@flogat you may want to look at commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/3349ced44728aa5586f04d00d410ccd1b5e9a832 to verify if that is what was intended.

**Comment by Tcheutchoua-Steve** [comment]
Implemented in https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/3349ced44728aa5586f04d00d410ccd1b5e9a832
