### ISSUE TITLE
ServerListTable - not filling all the space of the window

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#7]
Server List Table is too small, it should fill the remaining space, which I colored yellow in this screenshot:
![image](https://user-images.githubusercontent.com/12492529/56869011-af948f00-69fa-11e9-9ac6-38e17f1760ff.png)

**Comment by Tcheutchoua-Steve** [comment]
Solved with commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/b698d5342e731646cc777da8e90c5fdd3f57aa40
