### ISSUE TITLE
Server List Table - Shellfire VPN Premium Info Button

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#8]
The Premium Info Button (only shown when using a "Free" type vpn account) is not working:
![image](https://user-images.githubusercontent.com/12492529/56869019-d94db600-69fa-11e9-88a3-d45a586212fc.png)

In the old Shellfire VPN version, it was displaying a sophisticated Comparison Table. You can abandon this table and simply open a browser with the response from webservice.getUrlPremiumInfo()

**Comment by Tcheutchoua-Steve** [comment]
Resolved in commit https://github.com/Tcheutchoua-Steve/shellfire-vpn/commit/f8995634f9ad5e5cd4abc35141a4a6c686c8af32
