### ISSUE TITLE
Menu - different vertical gaps between menu items

### ISSUE THREAD

**Issue by flogat** [Tcheutchoua-Steve/shellfire-vpn#9]
There are 3 menu items:
Connection
Server List
USA Streams

Between "Connection" and "Server List", there is larger gap than between "Server List" and "USA Streeams". Please make the upper of the 2 gaps smaller, so that they are both equally large as the one between "Server List" and "Usa Streams":

![image](https://user-images.githubusercontent.com/12492529/56869052-71e43600-69fb-11e9-9d87-09144ffbf334.png)

![image](https://user-images.githubusercontent.com/12492529/56869056-7f99bb80-69fb-11e9-8e53-14624e73384f.png)

**Comment by Tcheutchoua-Steve** [comment]
Resolved in commit e9c1cc53921f5472016b0723b0cd2b5abc0be48c
